### ISSUE TITLE
Node Week 5 Homework Feedback

### ISSUE THREAD

**Issue by r0hitsharma** [YousofMersal/Hackyourfuture#1]
Try and keep anything you would need within a class, as a method, or property or dependency. In this case, when you would need to persist data, you'd probably refactor it so that the filename is available within.

https://github.com/YousofMersal/Hackyourfuture/blob/a91f008991e6d6ef0d41b205c7244760b30da537/NodeWeek5/Homework/notes.js#L22-L24

Could merge into one call (and would be better that way, so that you don't use public folder for anything else), unless you're indeed going for multiple roots (https://expressjs.com/en/resources/middleware/serve-static.html#multiple-roots) :

https://github.com/YousofMersal/Hackyourfuture/blob/a91f008991e6d6ef0d41b205c7244760b30da537/NodeWeek5/Homework/server.js#L9-L10

**Comment by YousofMersal** [comment]
I moved `const dbContent = fs.readFileSync('./db/db.json', 'utf-8')` into the NoteList constructor, and merged the calls into a singe root `app.use(express.static(__dirname + '/public'))`.
